/**
 * Application hook: wallet session + public contract state + circuit calls.
 *
 * All chain interaction is real:
 *  - connection goes through the Midnight Lace DApp Connector,
 *  - proofs are generated by the wallet's prover (locally, on the user's
 *    device) with an optional local proof-server fallback,
 *  - transactions are balanced and submitted by the wallet, and
 *  - every value shown after a call comes from the finalized transaction and
 *    the Preprod indexer — nothing is fabricated.
 */
import { useCallback, useEffect, useRef, useState } from 'react';

import { findDeployedContract } from '@midnight-ntwrk/midnight-js-contracts';
import type { MidnightProviders, PublicDataProvider } from '@midnight-ntwrk/midnight-js-types';

import {
  compiledAuctionContract,
  decodeAuctionState,
  type AuctionPrivateState,
} from '../midnight/auctionContract';
import { CONTRACT_ADDRESS, PRIVATE_STATE_ID, TARGET_NETWORK_ID } from '../midnight/config';
import {
  createBrowserProviders,
  createPublicDataReader,
  type BrowserProviders,
  type ProvingStage,
} from '../midnight/providers';
import {
  connectWallet,
  isWalletInjected,
  WalletError,
  type WalletSession,
} from '../midnight/wallet';

export interface TxResult {
  txHash: string;
  txId: string;
  circuitName: string;
  status: 'success';
  message: string;
  timestamp: string;
  blockHeight?: number;
}

/** The subset of `findDeployedContract`'s result this dApp uses. */
interface FoundAuctionContract {
  callTx: Record<
    'bid' | 'close_auction',
    () => Promise<{
      public: { txId: string; txHash: string; blockHeight: number; blockTimestamp?: number };
    }>
  >;
}

/**
 * `findDeployedContract` is generic over the statically known Compact contract
 * type. The browser loads the compiled contract as a module binding, so the
 * generics are widened here once instead of being scattered through the call
 * sites.
 */
const findContract = findDeployedContract as unknown as (
  providers: MidnightProviders,
  options: {
    compiledContract: unknown;
    contractAddress: string;
    privateStateId: string;
    initialPrivateState?: AuctionPrivateState;
  },
) => Promise<FoundAuctionContract>;

export interface UseMidnightState {
  isConnected: boolean;
  isConnecting: boolean;
  walletDetected: boolean;
  walletAddress: string | null;
  walletBalance: string | null;
  network: string;
  contractAddress: string;
  highestBid: number;
  highestBidder: string;
  isAuctionActive: boolean;
  isReadingState: boolean;
  isProving: boolean;
  provingStep: string;
  isSubmitting: boolean;
  txResult: TxResult | null;
  error: string | null;
  /** Wallet/connection failures, rendered by the wallet card only. */
  walletError: string | null;
  connect: () => Promise<void>;
  disconnect: () => void;
  callBidCircuit: (privateBidAmount: number) => Promise<boolean>;
  callCloseCircuit: () => Promise<boolean>;
  refreshPublicState: () => Promise<boolean>;
  clearError: () => void;
}

/** Stage descriptions rendered while a circuit call is in flight. */
const STAGE_STEPS: Record<ProvingStage, string> = {
  witness: '1/4 Preparing private witness — your bid stays in this browser',
  proving: '2/4 Generating zero-knowledge proof locally on your device',
  submitting: '3/4 Balancing and submitting the transaction through Lace',
  confirming: '4/4 Waiting for confirmation on the Preprod indexer',
};

const READ_ERROR_TEXT =
  'Could not read the contract from the Preprod indexer. It may still be syncing — retry in a moment.';

function formatBalance(balance: bigint | null): string | null {
  if (balance === null) return null;
  return `${balance.toLocaleString('en-US')} tNIGHT`;
}

function formatTimestamp(unixSeconds?: number): string {
  if (!unixSeconds) return new Date().toLocaleTimeString();
  return new Date(unixSeconds * 1000).toLocaleString();
}

/**
 * Turns SDK failures into actionable, non-leaking messages. Private witness
 * values (the bid) are deliberately never echoed back into the UI.
 */
function humanizeError(error: unknown): string {
  if (error instanceof WalletError) return error.message;

  const message = error instanceof Error ? error.message : String(error ?? 'Unknown error');

  if (/Bid is not high enough|assertion failed/i.test(message)) {
    return (
      'Circuit assertion failed locally while generating the proof: your bid is not strictly ' +
      'higher than the current highest bid. No transaction was broadcast, so losing bids never ' +
      'touch the chain.'
    );
  }
  if (/Auction is already closed/i.test(message)) {
    return 'Circuit rejected the call: the auction is closed on-chain.';
  }
  if (/getProvingProvider|not (yet )?supported|unsupported/i.test(message)) {
    return (
      'The connected wallet cannot generate proofs. Enable proving in Lace, or run a local proof ' +
      'server with `npm run proof-server:start` and rebuild with VITE_PROOF_SERVER_URL=http://127.0.0.1:6300.'
    );
  }
  if (/ECONNREFUSED|Failed to connect to Proof Server|fetch failed|load failed|network error/i.test(message)) {
    return (
      'No proving backend is reachable. Run `npm run proof-server:start` to start the local proof ' +
      `server, then reload. (${message})`
    );
  }
  if (/Insufficient Funds|Not enough Dust/i.test(message)) {
    return 'The wallet does not have enough tNIGHT/DUST to pay transaction fees. Fund it from the Preprod faucet and retry.';
  }
  if (/contract state|indexer|query/i.test(message)) return `${message}`;

  return message;
}

export function useMidnight(): UseMidnightState {
  const [isConnected, setIsConnected] = useState(false);
  const [isConnecting, setIsConnecting] = useState(false);
  const [walletDetected, setWalletDetected] = useState(false);
  const [walletAddress, setWalletAddress] = useState<string | null>(null);
  const [walletBalance, setWalletBalance] = useState<string | null>(null);
  const [network, setNetwork] = useState<string>(TARGET_NETWORK_ID);

  const [highestBid, setHighestBid] = useState<number>(0);
  const [highestBidder, setHighestBidder] = useState<string>('—');
  const [isAuctionActive, setIsAuctionActive] = useState<boolean>(true);
  const [isReadingState, setIsReadingState] = useState<boolean>(false);

  const [isProving, setIsProving] = useState(false);
  const [provingStep, setProvingStep] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [txResult, setTxResult] = useState<TxResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [walletError, setWalletError] = useState<string | null>(null);

  const sessionRef = useRef<WalletSession | null>(null);
  const providersRef = useRef<Promise<BrowserProviders> | null>(null);
  const readerRef = useRef<PublicDataProvider | null>(null);

  const getReader = useCallback((): PublicDataProvider => {
    if (!readerRef.current) readerRef.current = createPublicDataReader();
    return readerRef.current;
  }, []);

  /** Real stage transitions reported by the proof/balance/submit pipeline. */
  const handleStage = useCallback((stage: ProvingStage) => {
    if (stage === 'proving') {
      setIsProving(true);
      setIsSubmitting(false);
    } else {
      setIsProving(false);
      setIsSubmitting(true);
    }
    setProvingStep(STAGE_STEPS[stage]);
  }, []);

  const refreshPublicState = useCallback(async (): Promise<boolean> => {
    setIsReadingState(true);
    try {
      const contractState = await getReader().queryContractState(CONTRACT_ADDRESS);
      const decoded = decodeAuctionState(contractState);
      if (!decoded) {
        setError((previous) => previous ?? READ_ERROR_TEXT);
        return false;
      }
      setHighestBid(decoded.highestBid);
      setHighestBidder(decoded.highestBidder);
      setIsAuctionActive(decoded.isAuctionActive);
      setError((previous) => (previous === READ_ERROR_TEXT ? null : previous));
      return true;
    } catch (err) {
      console.error('[midnight] failed to read contract state', err);
      setError((previous) => previous ?? READ_ERROR_TEXT);
      return false;
    } finally {
      setIsReadingState(false);
    }
  }, [getReader]);

  const ensureProviders = useCallback(
    (session: WalletSession): Promise<BrowserProviders> => {
      if (!providersRef.current) {
        providersRef.current = createBrowserProviders(session, handleStage).catch((err) => {
          providersRef.current = null;
          throw err;
        });
      }
      return providersRef.current;
    },
    [handleStage],
  );

  const connect = useCallback(async () => {
    setError(null);
    setWalletError(null);
    setIsConnecting(true);
    setWalletDetected(isWalletInjected());
    try {
      const session = await connectWallet();
      sessionRef.current = session;
      providersRef.current = null;
      setWalletAddress(session.unshieldedAddress);
      setWalletBalance(formatBalance(session.balance));
      setNetwork(session.networkId);
      setIsConnected(true);
      await refreshPublicState();
    } catch (err) {
      sessionRef.current = null;
      setIsConnected(false);
      setWalletAddress(null);
      setWalletBalance(null);
      setWalletError(humanizeError(err));
    } finally {
      setIsConnecting(false);
    }
  }, [refreshPublicState]);

  const disconnect = useCallback(() => {
    sessionRef.current = null;
    providersRef.current = null;
    setIsConnected(false);
    setWalletAddress(null);
    setWalletBalance(null);
    setTxResult(null);
    setError(null);
    setWalletError(null);
    setIsProving(false);
    setIsSubmitting(false);
    setProvingStep('');
  }, []);

  const clearError = useCallback(() => {
    setError(null);
    setWalletError(null);
  }, []);

  const callCircuit = useCallback(
    async (circuitName: 'bid' | 'close_auction', privateState?: AuctionPrivateState): Promise<boolean> => {
      const session = sessionRef.current;
      if (!session) {
        setError('Connect your Lace wallet before calling a circuit.');
        return false;
      }
      if (!isAuctionActive && circuitName === 'bid') {
        setError('The auction is closed on-chain. No further bids are accepted.');
        return false;
      }

      setError(null);
      setTxResult(null);
      setIsProving(true);
      setProvingStep(STAGE_STEPS.witness);

      try {
        const browser = await ensureProviders(session);

        if (privateState) {
          browser.privateStateProvider.setContractAddress(CONTRACT_ADDRESS);
          await browser.privateStateProvider.set(PRIVATE_STATE_ID, privateState);
        }

        const found = await findContract(browser.providers, {
          compiledContract: compiledAuctionContract,
          contractAddress: CONTRACT_ADDRESS,
          privateStateId: PRIVATE_STATE_ID,
          ...(privateState ? { initialPrivateState: privateState } : {}),
        });

        const result = await found.callTx[circuitName]();
        const { txId, txHash, blockHeight, blockTimestamp } = result.public;

        await refreshPublicState();

        setTxResult({
          txId,
          txHash,
          blockHeight,
          circuitName: `${circuitName}()`,
          status: 'success',
          message: 'Zero-knowledge proof verified and the transaction was finalized on Preprod.',
          timestamp: formatTimestamp(blockTimestamp),
        });
        return true;
      } catch (err) {
        console.error(`[midnight] ${circuitName} call failed`, err);
        setError(humanizeError(err));
        return false;
      } finally {
        setIsProving(false);
        setIsSubmitting(false);
        setProvingStep('');
      }
    },
    [ensureProviders, isAuctionActive, refreshPublicState],
  );

  const callBidCircuit = useCallback(
    (privateBidAmount: number): Promise<boolean> => {
      if (!Number.isFinite(privateBidAmount) || privateBidAmount <= 0) {
        setError('Enter a valid bid amount greater than zero.');
        return Promise.resolve(false);
      }
      const session = sessionRef.current;
      if (!session) {
        setError('Connect your Lace wallet before calling a circuit.');
        return Promise.resolve(false);
      }
      // The amount and the bidder id live only in the local private state that
      // feeds the `my_bid` / `my_public_key` witnesses. Neither is a circuit
      // argument, so neither can appear in the transaction.
      return callCircuit('bid', {
        my_bid: privateBidAmount,
        my_public_key: session.publicIdentifier,
      });
    },
    [callCircuit],
  );

  const callCloseCircuit = useCallback((): Promise<boolean> => callCircuit('close_auction'), [callCircuit]);

  // Detect the wallet on mount and load the public contract state without
  // requiring a connection (public data is public).
  useEffect(() => {
    setWalletDetected(isWalletInjected());
    void refreshPublicState();

    const onEip1193Event = () => setWalletDetected(isWalletInjected());
    window.addEventListener('midnight#initialized', onEip1193Event);
    return () => window.removeEventListener('midnight#initialized', onEip1193Event);
  }, [refreshPublicState]);

  return {
    isConnected,
    isConnecting,
    walletDetected,
    walletAddress,
    walletBalance,
    network,
    contractAddress: CONTRACT_ADDRESS,
    highestBid,
    highestBidder,
    isAuctionActive,
    isReadingState,
    isProving,
    provingStep,
    isSubmitting,
    txResult,
    error,
    walletError,
    connect,
    disconnect,
    callBidCircuit,
    callCloseCircuit,
    refreshPublicState,
    clearError,
  };
}
